# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script:
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  displayName: 'enable arm64 emulation'

- script:
    docker build -f Dockerfile -t evergiven.azurecr.io/micropcr:latest .
- task: Docker@2
  inputs:
    containerRegistry: 'evergiven'
    repository: 'micropcr'
    command: 'push'
    tags:
      latest