# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub se22m055'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
        arguments: '--platform linux/amd64,linux/arm64'
  
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub se22m055'
        repository: 'se22m055 / microservice'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest

