version: '3.4'
services:
  microservice:
    image: se22m055/microservice:latest
    env_file: .env
    ports:
      - ${LISTEN_PORT}:80
  mongo:
    image: mongo
    restart: always
    env_file: .env
    ports:
      - ${MONGO_DB_PORT}:27017