apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcr-deployment
  labels:
    app: pcr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pcr
  template:
    metadata:
      labels:
        app: pcr
    spec:
      containers:
      - name: microservice
        image: se22m055/microservice:latest
        ports:
        - containerPort: 80
        env:
        - name: MONGO_DB_HOST
          value: "host.docker.internal"
        - name: MONGO_DB_PORT
          value: "27017"
        - name: LISTEN_PORT
          value: "80"   